"""initial schema

Revision ID: 524fea4317a9
Revises: 
Create Date: 2026-08-11 22:58:30.862292
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Нужен для колонок с собственным типом TZDateTime, который рендерит autogenerate
import app.models.base  # noqa: F401

revision: str = '524fea4317a9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('EXPENSE', 'INCOME', name='categorykind', native_enum=False, length=16), nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)

    op.create_table('sync_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=26), nullable=False),
    sa.Column('op', sa.Enum('UPSERT', 'DELETE', name='outboxop', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('processed_at', app.models.base.TZDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_outbox'))
    )
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_outbox_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_outbox_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_outbox_processed_at'), ['processed_at'], unique=False)

    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('accounts',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('CASH', 'CARD', 'SAVINGS', 'OTHER', name='accountkind', native_enum=False, length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=26), nullable=True),
    sa.Column('opening_balance_minor', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_accounts_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_shared'), ['is_shared'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_owner_id'), ['owner_id'], unique=False)

    op.create_table('category_rules',
    sa.Column('pattern', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.String(length=26), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_rules_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_rules'))
    )
    op.create_table('transactions',
    sa.Column('occurred_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', name='transactiontype', native_enum=False, length=16), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('account_id', sa.String(length=26), nullable=False),
    sa.Column('counter_account_id', sa.String(length=26), nullable=True),
    sa.Column('category_id', sa.String(length=26), nullable=True),
    sa.Column('author_id', sa.String(length=26), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('APP', 'BOT', 'SHEET', 'IMPORT', name='txsource', native_enum=False, length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('deleted_at', app.models.base.TZDateTime(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', app.models.base.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.models.base.TZDateTime(), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_transactions_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_transactions_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counter_account_id'], ['accounts.id'], name=op.f('fk_transactions_counter_account_id_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('external_id', name=op.f('uq_transactions_external_id'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_transactions_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_transactions_period', ['deleted_at', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)

    op.create_table('tx_splits',
    sa.Column('transaction_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('share_minor', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_tx_splits_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tx_splits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tx_splits'))
    )
    with op.batch_alter_table('tx_splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tx_splits_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index('ix_tx_splits_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tx_splits', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_splits_user')
        batch_op.drop_index(batch_op.f('ix_tx_splits_transaction_id'))

    op.drop_table('tx_splits')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index('ix_transactions_period')
        batch_op.drop_index('ix_transactions_occurred_at')
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_author_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    op.drop_table('category_rules')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_shared'))
        batch_op.drop_index(batch_op.f('ix_accounts_archived'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('sync_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_outbox_processed_at'))
        batch_op.drop_index(batch_op.f('ix_sync_outbox_entity_id'))
        batch_op.drop_index(batch_op.f('ix_sync_outbox_entity'))

    op.drop_table('sync_outbox')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_kind'))
        batch_op.drop_index(batch_op.f('ix_categories_archived'))

    op.drop_table('categories')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
